<script lang="ts">
	import { fade } from 'svelte/transition';
</script>

<div class="max-w-2xl mx-auto px-4 py-12 sm:py-20" in:fade={{ duration: 300 }}>
	<div class="terminal-box p-6 sm:p-8">
		<div class="flex items-center gap-3 mb-6 pb-4 border-b border-vibe-border">
			<span class="text-vibe-mint">$</span>
			<span class="text-vibe-muted text-sm">terms_of_service</span>
		</div>

		<h1 class="text-2xl font-bold text-vibe-text mb-6">Terms of Service</h1>
		<p class="text-vibe-muted text-xs mb-6">Last updated: January 2026</p>

		<div class="space-y-6 text-vibe-text text-sm">
			<section>
				<h2 class="text-vibe-mint font-semibold mb-2">The Service</h2>
				<p class="text-vibe-muted">Vibeship IdeaRater is a free tool that uses AI to evaluate startup ideas. It provides entertainment and general feedback - not professional business advice.</p>
			</section>

			<section>
				<h2 class="text-vibe-mint font-semibold mb-2">Your Ideas</h2>
				<ul class="list-disc list-inside text-vibe-muted space-y-1">
					<li>You own your ideas. We claim no rights to anything you submit.</li>
					<li>We don't store your ideas. They're processed and discarded immediately.</li>
					<li>Don't submit confidential information you wouldn't share publicly.</li>
				</ul>
			</section>

			<section>
				<h2 class="text-vibe-mint font-semibold mb-2">AI-Generated Content</h2>
				<ul class="list-disc list-inside text-vibe-muted space-y-1">
					<li>Scores and feedback are generated by AI (Claude by Anthropic).</li>
					<li>Results are for entertainment and general guidance only.</li>
					<li>We make no guarantees about accuracy or business outcomes.</li>
					<li>A high score doesn't guarantee success. A low score doesn't mean failure.</li>
				</ul>
			</section>

			<section>
				<h2 class="text-vibe-mint font-semibold mb-2">Usage Limits</h2>
				<ul class="list-disc list-inside text-vibe-muted space-y-1">
					<li>10 idea ratings per day per user.</li>
					<li>Don't abuse the service or attempt to circumvent limits.</li>
					<li>We reserve the right to block abusive users.</li>
				</ul>
			</section>

			<section>
				<h2 class="text-vibe-mint font-semibold mb-2">Disclaimer</h2>
				<p class="text-vibe-muted">THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND. WE ARE NOT LIABLE FOR ANY DECISIONS YOU MAKE BASED ON THE FEEDBACK PROVIDED. USE AT YOUR OWN RISK.</p>
			</section>

			<section>
				<h2 class="text-vibe-mint font-semibold mb-2">Changes</h2>
				<p class="text-vibe-muted">We may update these terms. Continued use means you accept the changes.</p>
			</section>

			<section>
				<h2 class="text-vibe-mint font-semibold mb-2">Contact</h2>
				<p class="text-vibe-muted">Questions? Reach out at <a href="mailto:hello@vibeship.co" class="text-vibe-mint hover:underline">hello@vibeship.co</a></p>
			</section>
		</div>

		<div class="mt-8 pt-4 border-t border-vibe-border">
			<a href="/" class="text-vibe-mint text-sm hover:underline">&larr; Back to IdeaRater</a>
		</div>
	</div>
</div>
